$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: batch-deployment-02
endpoint_name: ep-batch-oh4ml-01
code_configuration:
  code: ../scripts
  scoring_script: score-diabetes.py
model: azureml:diabetes_model_oh4ml@latest
environment: azureml:diabetes-env-02@latest
compute: azureml:demo-cpucluster1
resources:
  instance_count: 2
max_concurrency_per_instance: 2
mini_batch_size: 10
output_action: append_row
output_file_name: predictions.csv
retry_settings:
  max_retries: 3
  timeout: 30
error_threshold: -1
logging_level: info